---
# Labels names are important as they are used by Release Drafter to decide
# regarding where to record them in changelog or if to skip them.
#
# The repository labels will be automatically configured using this file and
# the GitHub Action https://github.com/marketplace/actions/github-labeler.

# ----------------------------------
# CHANGES
# ----------------------------------
- name: "changes/major"
  description: "Breaking Changes"
  color: "bfd4f2"

- name: "changes/minor"
  description: "Feature Enhancements"
  color: "fef2c0"

- name: "changes/patch"
  description: "Maintenance tasks"
  color: "0366d6"

# ----------------------------------
# TYPE
# ----------------------------------
- name: "type/refactoring"
  description: "Refactoring"
  color: "ef67c4"

- name: "type/bug"
  description: "Something isn't working"
  color: "d73a4a"

- name: "type/documentation"
  description: "Improvements or additions to documentation"
  color: "0075ca"

- name: "type/duplicate"
  description: "This issue or pull request already exists"
  color: "cfd3d7"

- name: "type/feature"
  description: "New feature or request"
  color: "a2eeef"

- name: "type/question"
  description: "Further information is requested"
  color: "d876e3"

- name: "type/deprecated"
  description: "Removals and deprecations"
  color: "d876e3"

# ----------------------------------
# EFFORT
# ----------------------------------
- name: "effort/high"
  description: "This issue should be completed in more than a day"
  color: "b60205"

- name: "effort/medium"
  description: "This issue should be completed in a less than a day"
  color: "ff9f1c"

- name: "effort/low"
  description: "This issue should be completed in a couple of hours"
  color: "ffcc00"

# ----------------------------------
# SEVERITY
# ----------------------------------
- name: "priority/1"
  description: "This issue must be fixed/implemented ASAP, it's a blocker for a release"
  color: "b60205"

- name: "priority/2"
  description: "This issue stalls work on the project or its dependents, it's a blocker for a release"
  color: "ff9f1c"

- name: "priority/3"
  description: "Not blocking but should be fixed soon"
  color: "ffcc00"

- name: "priority/4"
  description: "Low priority and doesn't need to be rushed"
  color: "cfda2c"

# ----------------------------------
# STATUS
# ----------------------------------
- name: "state/help"
  description: "Extra attention is needed"
  color: "008672"

- name: "state/blocked"
  description: "The issue is currently blocked and cannot be resolved."
  color: "e34918"

- name: "state/draft"
  description: "The redaction of the issue is still a work in progress"
  color: "dcb518"

- name: "state/need-triage"
  description: "This issue needs to be triaged"
  color: "333333"

- name: "state/need-more-info"
  description: "This issue needs more information"
  color: "cccccc"

- name: "state/need-testing"
  description: "This issue is ready and needs to be tested."
  color: "cccccc"

- name: "state/backlog"
  description: "This issue is part of the backlog"
  color: "eeeeee"

- name: "state/planned"
  description: "This issue is planned to be worked on in an upcoming release."
  color: "eeeeee"

- name: "state/not-reproducible"
  description: "Unable to reproduce this issue."
  color: "eeeeee"

- name: "state/wont-fix"
  description: "Issue has been closed and won't be fix/implemented."
  color: "eeeeee"

# ----------------------------------
# CI
# ----------------------------------
- name: "ci/skip-changelog"
  description: "This will not be added to release notes"
  color: "dddddd"
