---
# Format and labels used aim to match those used by Ansible project
name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
categories:
  - title: "🚀 Breaking Changes"
    labels:
      - "changes/major"

  - title: "🔧 Minor Changes"
    labels:
      - "changes/minor"
      - "type/feature"
      - "type/refactoring"

  - title: "🐛 Patch & Bug Fixes"
    labels:
      - "type/bug"
      - "changes/patch"

  - title: "📖 Documentation Change"
    labels:
      - "type/documentation"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
exclude-labels:
  - "ci/skip-changelog"
  - "type/duplicate"

autolabeler:
  - label: "ci/skip-changelog"
    title: "/chore/i"
  - label: "type/bug"
    title: "/fix/i"
  - label: "type/feature"
    title: "/(enhance|improve|feature)/i"
  - label: "type/deprecated"
    title: "/deprecat/i"

template: |
  ## Changes

  $CHANGES

  Kudos goes to: $CONTRIBUTORS
