---
major-labels: ['changes/major', 'type/breaking-change']
minor-labels: ['changes/minor', 'type/feature', 'type/refactoring']
patch-labels: ['changes/patch', 'type/bug', 'type/housekeeping', 'type/documentation']
