---
# yamllint disable rule:truthy
name: Publish Infrahub Sync Package

on:
  workflow_call:
    inputs:
      runs-on:
        description: "The OS to run the job on"
        required: false
        default: "ubuntu-22.04"
        type: string
      version:
        type: string
        required: false
        description: The string to extract semver labels from.
        default: ''
      publish:
        type: boolean
        description: Wether to publish the package to Pypi
        required: false
        default: false

jobs:
  publish_to_pypi:
    name: "Publish Infrahub SDK to PyPI"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"

      - name: "Install Poetry"
        uses: "snok/install-poetry@v1"
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: "Check out repository code"
        uses: "actions/checkout@v4"

      - name: "Cache poetry venv"
        uses: "actions/cache@v4"
        id: "cached-poetry-dependencies"
        with:
          path: "./infrahub_sync/.venv"
          key: "venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}"

      - name: "Install Dependencies"
        run: "poetry install"
        working-directory: "./infrahub_sync"
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: "Add PyPI secret"
        run: "poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}"

      - name: "Poetry build"
        run: "poetry build"
        working-directory: "./infrahub_sync"

      - name: "show output"
        run: "ls -la dist/"
        working-directory: "./infrahub_sync"

      - name: "Poetry push PyPI"
        run: "poetry publish"
        working-directory: "./infrahub_sync"
